import { EXTRACTION_PROVIDERS, LEGACY_EXTRACTION_PROVIDERS } from '@balance/types';

export const DEFAULT_EXTRACTION_PROVIDER = 'paddleocr';
export const EXTRACTION_PIPELINE_VERSION = 'v0.5.0-open-ocr';
export const ACTIVE_EXTRACTION_PROVIDERS = new Set<string>(EXTRACTION_PROVIDERS);
export const LEGACY_DISABLED_EXTRACTION_PROVIDERS = new Set<string>(LEGACY_EXTRACTION_PROVIDERS);
